baseURL: https://nafo.ukrainians.org.au/

title: NAFO

defaultContentLanguage: en-au
timeZone: Australia/Sydney

enableRobotsTXT: true

disableKinds: [ "RSS" ]

# Disable default taxonomies.
taxonomies:

menu:
  main:
    - name: What is NAFO?
      pageRef: /
      weight: 10

    - name: Campaigns
      pageRef: /campaigns
      weight: 20

languages:
  en-au:
    languageName: English
    weight: 1
    Params:
      image: '/images/flags/au.svg'

  uk:
    languageName: Українська
    weight: 2
    Params:
      image: '/images/flags/ua.svg'

  pl:
    languageName: Polski
    weight: 3
    Params:
      image: '/images/flags/pl.svg'

  es:
    languageName: Español
    weight: 4
    Params:
      image: '/images/flags/es.svg'

params:
  images: [ '/images/social.png' ]

deployment:
  targets:
    name: aws-s3
    URL: s3://nafo.ukrainians.org.au?region=ap-southeast-2

  matchers:
    - pattern: ^sitemap\\.xml$
      cacheControl: public, s-maxage=604800, max-age=86400 #7d,1d
      contentType: application/xml
      gzip: true

    - pattern: ^.+\\.(css|js)$
      cacheControl: public, immutable, max-age=31536000 #1y
      gzip: true

    - pattern: (?i)^.+_hu[0-9a-f]{32}_.+\\.(jpg|jpeg|gif|png|webp)$
      cacheControl: public, immutable, max-age=31536000 #1y
      gzip: true

    - pattern: (?i)^.+\\.(jpg|jpeg|gif|png|webp|mp4|woff|woff2)$
      cacheControl: public, s-maxage=7776000, max-age=604800 #90d,7d
      gzip: true

    - pattern: ^.+\\.(html|xml|json|txt)$
      cacheControl: public, s-maxage=604800, max-age=3600 #7d,1h
      gzip: true