name: Deploy to Xumo

on:
  push:
    branches:
      - master

jobs:
  deploy-dev:
    name: Build And Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v1

      - name: Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.110.0'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2

      - name: Install Prerequisites
        run: |
          make install

      - name: Build & Deploy
        run: |
          hugo
          make deploy
          make sync